name: Install Dependencies for building the project
on: 
  push:
    branches: 
      - main
strategy:
  matrix:
    os: [ubuntu-latest, macos-latest]


jobs:
  flutter_install:
    name: Install Flutter
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'oracle'
          cache: 'gradle'
      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          version: '3.7.7'
          cache: true
      
